-- IQ_INDICATOR_MONTHLY: 지표 월간 캐싱 테이블
-- 월 + 모델 + 공정 단위로 NG/TOTAL/PPM 저장 + 대책서번호
CREATE TABLE IQ_INDICATOR_MONTHLY (
  TARGET_MONTH      VARCHAR2(7)   NOT NULL,
  ITEM_CODE         VARCHAR2(50)  NOT NULL,
  PROCESS_CODE      VARCHAR2(10)  NOT NULL,
  NG_COUNT          NUMBER        DEFAULT 0,
  TOTAL_COUNT       NUMBER        DEFAULT 0,
  PPM               NUMBER        DEFAULT 0,
  COUNTERMEASURE_NO VARCHAR2(50),
  CREATED_DATE      DATE          DEFAULT SYSDATE,
  UPDATED_DATE      DATE          DEFAULT SYSDATE,
  CONSTRAINT PK_IQ_INDICATOR_MONTHLY PRIMARY KEY (TARGET_MONTH, ITEM_CODE, PROCESS_CODE)
);

COMMENT ON TABLE IQ_INDICATOR_MONTHLY IS '지표 월간 캐싱 — 모델×공정별 NG/PPM + 대책서';
COMMENT ON COLUMN IQ_INDICATOR_MONTHLY.TARGET_MONTH IS '대상 월 (YYYY/MM)';
COMMENT ON COLUMN IQ_INDICATOR_MONTHLY.ITEM_CODE IS '모델 코드 (IP_PRODUCT_2D_BARCODE.ITEM_CODE)';
COMMENT ON COLUMN IQ_INDICATOR_MONTHLY.PROCESS_CODE IS '공정 코드 (ICT/HIPOT/FT/BURNIN/ATE)';
COMMENT ON COLUMN IQ_INDICATOR_MONTHLY.COUNTERMEASURE_NO IS '대책서번호 (NULL이면 미등록)';
