-- 설비이상 시드 데이터: LINE_STATUS_CODE에 공정코드 직접 사용
-- P51~P60: ICT, HIPOT, FT, BURNIN, ATE
-- P81~P86: IMAGE, SETTV

BEGIN
  -- P51: ICT 45분, HIPOT 20분, FT 75분(C급), BURNIN 15분, ATE 30분
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P51', 'ICT', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+8/24, TRUNC(SYSDATE)+8/24+45/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P51', 'HIPOT', TRUNC(SYSDATE), 2, TRUNC(SYSDATE)+9/24, TRUNC(SYSDATE)+9/24+20/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P51', 'FT', TRUNC(SYSDATE), 3, TRUNC(SYSDATE)+10/24, TRUNC(SYSDATE)+10/24+75/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P51', 'BURNIN', TRUNC(SYSDATE), 4, TRUNC(SYSDATE)+11/24, TRUNC(SYSDATE)+11/24+15/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P51', 'ATE', TRUNC(SYSDATE), 5, TRUNC(SYSDATE)+12/24, TRUNC(SYSDATE)+12/24+30/1440, 'SEED', SYSDATE);

  -- P52: ICT 10분, FT 25분, ATE 65분(C급)
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P52', 'ICT', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+8/24, TRUNC(SYSDATE)+8/24+10/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P52', 'FT', TRUNC(SYSDATE), 2, TRUNC(SYSDATE)+9/24, TRUNC(SYSDATE)+9/24+25/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P52', 'ATE', TRUNC(SYSDATE), 3, TRUNC(SYSDATE)+10/24, TRUNC(SYSDATE)+10/24+65/1440, 'SEED', SYSDATE);

  -- P53: HIPOT 90분(C급), BURNIN 40분
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P53', 'HIPOT', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+8/24, TRUNC(SYSDATE)+8/24+90/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P53', 'BURNIN', TRUNC(SYSDATE), 2, TRUNC(SYSDATE)+10/24, TRUNC(SYSDATE)+10/24+40/1440, 'SEED', SYSDATE);

  -- P54: ICT 5분, FT 8분 (정상 — 소량 정지)
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P54', 'ICT', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+9/24, TRUNC(SYSDATE)+9/24+5/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P54', 'FT', TRUNC(SYSDATE), 2, TRUNC(SYSDATE)+10/24, TRUNC(SYSDATE)+10/24+8/1440, 'SEED', SYSDATE);

  -- P55: ATE 120분(C급), ICT 35분
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P55', 'ATE', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+8/24, TRUNC(SYSDATE)+8/24+120/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P55', 'ICT', TRUNC(SYSDATE), 2, TRUNC(SYSDATE)+11/24, TRUNC(SYSDATE)+11/24+35/1440, 'SEED', SYSDATE);

  -- P56: FT 55분, BURNIN 70분(C급)
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P56', 'FT', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+8/24, TRUNC(SYSDATE)+8/24+55/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P56', 'BURNIN', TRUNC(SYSDATE), 2, TRUNC(SYSDATE)+10/24, TRUNC(SYSDATE)+10/24+70/1440, 'SEED', SYSDATE);

  -- P81: IMAGE 80분(C급), SETTV 25분
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P81', 'IMAGE', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+8/24, TRUNC(SYSDATE)+8/24+80/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P81', 'SETTV', TRUNC(SYSDATE), 2, TRUNC(SYSDATE)+10/24, TRUNC(SYSDATE)+10/24+25/1440, 'SEED', SYSDATE);

  -- P82: IMAGE 15분, SETTV 95분(C급)
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P82', 'IMAGE', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+9/24, TRUNC(SYSDATE)+9/24+15/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P82', 'SETTV', TRUNC(SYSDATE), 2, TRUNC(SYSDATE)+10/24, TRUNC(SYSDATE)+10/24+95/1440, 'SEED', SYSDATE);

  -- P83: IMAGE 45분, SETTV 50분
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P83', 'IMAGE', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+8/24, TRUNC(SYSDATE)+8/24+45/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P83', 'SETTV', TRUNC(SYSDATE), 2, TRUNC(SYSDATE)+10/24, TRUNC(SYSDATE)+10/24+50/1440, 'SEED', SYSDATE);

  -- P84: SETTV 110분(C급)
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P84', 'SETTV', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+8/24, TRUNC(SYSDATE)+8/24+110/1440, 'SEED', SYSDATE);

  -- P85: IMAGE 62분(C급), SETTV 10분
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P85', 'IMAGE', TRUNC(SYSDATE), 1, TRUNC(SYSDATE)+9/24, TRUNC(SYSDATE)+9/24+62/1440, 'SEED', SYSDATE);
  INSERT INTO IP_LINE_DAILY_OPERATION_HIST (LINE_CODE, LINE_STATUS_CODE, ACTUAL_DATE, LINE_OPERATION_SEQUENCE, START_DATE, END_DATE, ENTER_BY, ENTER_DATE)
  VALUES ('P85', 'SETTV', TRUNC(SYSDATE), 2, TRUNC(SYSDATE)+11/24, TRUNC(SYSDATE)+11/24+10/1440, 'SEED', SYSDATE);

  COMMIT;
END;
/
